spring:
  application:
    name: single-save

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 112091718765-b4l2tohi18av027s7fu35doogmpsb1t0.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/single_save
    username: single_save
    password: single_save

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/single_save
    user: single_save
    password: single_save
    locations: classpath:db/migration
    connect-retries: 10

  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

logging:
  level:
    root: INFO
    com.aleonisp.singlesave: INFO
    org.flywaydb: INFO
    org.springframework.boot.autoconfigure.flyway: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.r2dbc: WARN
    org.springframework.r2dbc.core: WARN
    io.r2dbc.postgresql: WARN
    reactor.netty: WARN